#!/data/data/io.neoterm/files/usr/bin/python3.6
# -*- coding: utf-8 -*-
age = 20
if age >= 18:
    print('your age is',age)
    print('adult')


age = 3
if age >= 18:
    print('your age is',age)
    print('adult')
else:
    print('your age is',age)
    print('teenager')
